<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="2" hostname="DESKTOP-09IB0QD" failures="2" tests="2" name="Default test(failed)(failed)" time="0.2" errors="0" timestamp="2023-06-08T08:05:56 IST">
  <testcase classname="com.selenium.code.TestNGDemo.retry.RetryTesteCasseDemo" name="test3" time="0.044">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.selenium.code.TestNGDemo.retry.RetryTesteCasseDemo.test3(RetryTesteCasseDemo.java:30)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- test3 -->
  <testcase classname="com.selenium.code.TestNGDemo.retry.RetryTesteCasseDemo" name="test2" time="0.011">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.selenium.code.TestNGDemo.retry.RetryTesteCasseDemo.test2(RetryTesteCasseDemo.java:24)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- test2 -->
  <testcase classname="com.selenium.code.TestNGDemo.retry.RetryTesteCasseDemo" name="test1" time="0.0">
    <ignored/>
  </testcase> <!-- test1 -->
  <testcase classname="com.selenium.code.TestNGDemo.retry.RetryTesteCasseDemo" name="test4" time="0.0">
    <ignored/>
  </testcase> <!-- test4 -->
</testsuite> <!-- Default test(failed)(failed) -->
